# Generated by Django 4.2.6 on 2023-10-13 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('IPAdresse', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('SNMPType', models.CharField(choices=[('1', 'Version 1'), ('2c', 'Version 2c'), ('3', 'Version 3')], default='1', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='OID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('is_admin', models.BooleanField(default=False)),
                ('mail', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SurveillanceManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information_type', models.CharField(max_length=255)),
                ('data', models.CharField(max_length=255)),
                ('idMachine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informations', models.CharField(max_length=255)),
                ('is_error', models.BooleanField(default=False)),
                ('idMachine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Graphique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('x_label', models.CharField(max_length=255)),
                ('y_label', models.CharField(max_length=255)),
                ('x_info', models.CharField(max_length=255)),
                ('y_info', models.CharField(max_length=255)),
                ('idSurveillance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.surveillancemanager')),
            ],
        ),
    ]
