# Generated by Django 4.2.6 on 2023-10-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_machine_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='port',
            field=models.IntegerField(default=161),
        ),
    ]
