# Generated by Django 4.2.6 on 2023-10-27 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_oid_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveillancemanager',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 27, 21, 14, 45, 617510)),
        ),
    ]
