# Generated by Django 4.2.6 on 2023-11-04 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_surveillancemanager_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveillancemanager',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
