# Generated by Django 4.2.6 on 2023-11-05 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_alter_surveillancemanager_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
