# Generated by Django 4.2.6 on 2023-11-10 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_delete_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
