# Generated by Django 4.2.7 on 2023-11-12 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0010_logs_type_log_delete_graphique'),
    ]

    operations = [
        migrations.AddField(
            model_name='oid',
            name='is_Integer',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Graphique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('GraphiqueType', models.CharField(choices=[('1', 'Flêche'), ('2', 'Curseur'), ('3', 'Comparaison')], default='1', max_length=255)),
                ('axex', models.CharField(max_length=255)),
                ('axey', models.CharField(max_length=255)),
                ('ordre', models.IntegerField()),
                ('valeur_max', models.IntegerField()),
                ('OID1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OID1', to='configuration.oid')),
                ('OID2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OID2', to='configuration.oid')),
            ],
        ),
    ]
