# Generated by Django 4.2.7 on 2023-11-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0011_oid_is_integer_graphique'),
    ]

    operations = [
        migrations.AddField(
            model_name='oid',
            name='Donnee_fixe',
            field=models.BooleanField(default=False),
        ),
    ]
