# Generated by Django 4.2.7 on 2023-11-12 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0014_alter_graphique_graphiquetype_alter_graphique_axex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphique',
            name='OID2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OID2', to='configuration.oid'),
        ),
        migrations.AlterField(
            model_name='graphique',
            name='valeur_max',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
