# Generated by Django 4.2.7 on 2023-11-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0015_alter_graphique_oid2_alter_graphique_valeur_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphique',
            name='valeur_max',
            field=models.IntegerField(default=0),
        ),
    ]
