# Generated by Django 4.2.7 on 2023-11-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0016_alter_graphique_valeur_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphique',
            name='GraphiqueType',
            field=models.CharField(choices=[('Fleche', 'Fleche'), ('Curseur', 'Curseur'), ('Comparaison', 'Comparaison'), ('Texte', 'Texte')], default='1', max_length=255),
        ),
    ]
