# Generated by Django 4.2.6 on 2023-11-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0017_alter_graphique_graphiquetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphique',
            name='GraphiqueType',
            field=models.CharField(choices=[('Fleche', 'Fleche'), ('Curseur', 'Curseur'), ('Texte', 'Texte')], default='1', max_length=255),
        ),
    ]
