# Generated by Django 4.2.6 on 2023-11-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0019_remove_oid_is_integer'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphique',
            name='type_de_donnees_entree',
            field=models.CharField(choices=[('Texte', 'Texte'), ('Boolean', 'Boolean'), ('Heure', 'Heure'), ('Minutes', 'Minutes'), ('Secondes', 'Secondes')], default='Texte', max_length=255),
        ),
        migrations.AddField(
            model_name='graphique',
            name='type_de_donnees_sortie',
            field=models.CharField(choices=[('Texte', 'Texte'), ('Boolean', 'Boolean'), ('Heure', 'Heure'), ('Minutes', 'Minutes'), ('Secondes', 'Secondes')], default='Texte', max_length=255),
        ),
    ]
