# Generated by Django 4.2.7 on 2023-11-28 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0022_graphique_has_machine_ordre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphique',
            name='ordre',
        ),
    ]
