# Generated by Django 4.2.6 on 2023-11-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0023_remove_graphique_ordre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphique',
            name='type_de_donnees_entree',
            field=models.CharField(choices=[('Texte', 'Texte'), ('Entier', 'Entier'), ('Boolean', 'Boolean'), ('Heure', 'Heure'), ('Minute', 'Minute'), ('Seconde', 'Seconde'), ('Ratio', 'Ratio'), ('Pourcentage', 'Pourcentage')], default='Texte', max_length=255),
        ),
        migrations.AlterField(
            model_name='graphique',
            name='type_de_donnees_sortie',
            field=models.CharField(choices=[('Texte', 'Texte'), ('Entier', 'Entier'), ('Boolean', 'Boolean'), ('Heure', 'Heure'), ('Minute', 'Minute'), ('Seconde', 'Seconde'), ('Ratio', 'Ratio'), ('Pourcentage', 'Pourcentage')], default='Texte', max_length=255),
        ),
    ]
